insert into user values (1, 'Siamak', 'Codeenginell@gmail.com')
insert into user values (2, 'John', 'John@john.com')
insert into user values (3, 'Adam', 'adam@adam.com')

insert into category values (1, 'Products')
insert into category values (2, 'Utilities')
insert into category values (3, 'Pharmacy')
insert into category values (4, 'Technology')
insert into category values (5, 'Household')
insert into category values (6, 'Clothes')
insert into category values (7, 'Beauty')
insert into category values (8, 'Gifts')
insert into category values (9, 'Travelling')
insert into category values (10, 'Healthy')
insert into category values (11, 'Entertainment')

insert into option values (1, 'Purchase')
insert into option values (2, 'Receipt')

insert into expense values (default, 'New York Trip', '2019-06-16T17:00:00.00Z', 'New York', 100.0, 1,1, 1)
insert into expense values (default, 'Ford Mustang Payment', '2019-06-15T15:00:00.00Z', 'Los Angeles', 50.0, 2,1, 2)
insert into expense values (default, 'Grand Canyon Trip With Family', '2019-06-15T15:00:00.00Z', 'Arizona', 70.0, 3,1, 1)